name: "Test"

on:
    push:

jobs:
    test:
        name: Test (PHP ${{ matrix.php-versions }})
        runs-on: ubuntu-20.04

        strategy:
            fail-fast: false
            matrix:
                php-versions: ['8.0', '8.1', '8.2']

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    coverage: pcov
                    extensions: sockets

            -   name: Get Composer cache dir
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-php-${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ runner.os }}-php-${{ matrix.php-versions }}-composer-

            -   name: Install dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader

            -   name: Run PHPUnit
                run: vendor/bin/phpunit --coverage-clover=clover.xml

            -   name: Publish coverage
                uses: slavcodev/coverage-monitor-action@v1
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    coverage_path: clover.xml
